version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: 
      - .env
    ports:
      - "5432:5432"
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build: ./app
    ports:
      - "80:8080"
    depends_on:
      - db
    links:
      - db
    env_file: 
      - .env
